// Veriler; https://dummyjson.com/products adresinden elde edilmiştir.

export const dummyItems = [
  {
    id: 1,
    title: "iPhone 9",
    description: "An apple mobile which is nothing like apple",
    price: 549,
    stock: 94,
    vote: 57,
    thumbnail: "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg",
  },
  {
    id: 2,
    title: "iPhone X",
    description: "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    price: 899,
    stock: 34,
    vote: 48,
    thumbnail: "https://cdn.dummyjson.com/product-images/2/thumbnail.jpg",
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    description: "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    stock: 36,
    vote: 58,
    thumbnail: "https://cdn.dummyjson.com/product-images/3/thumbnail.jpg",
  },
  {
    id: 4,
    title: "OPPOF19",
    description: "OPPO F19 is officially announced on April 2021.",
    price: 280,
    stock: 123,
    vote: 14,
    thumbnail: "https://cdn.dummyjson.com/product-images/4/thumbnail.jpg",
  },
  {
    id: 5,
    title: "Huawei P30",
    description: "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
    price: 499,
    stock: 32,
    vote: 92,
    thumbnail: "https://cdn.dummyjson.com/product-images/5/thumbnail.jpg",
  },
  {
    id: 6,
    title: "MacBook Pro",
    description: "MacBook Pro 2021 with mini-LED display may launch between September, November",
    price: 1749,
    stock: 83,
    vote: 24,
    thumbnail: "https://cdn.dummyjson.com/product-images/6/thumbnail.png",
  },
  {
    id: 7,
    title: "Samsung Galaxy Book",
    description: "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    stock: 50,
    vote: 76,
    thumbnail: "https://cdn.dummyjson.com/product-images/7/thumbnail.jpg",
  },
  {
    id: 8,
    title: "Microsoft Surface Laptop 4",
    description: "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
    price: 1499,
    stock: 68,
    vote:74,
    thumbnail: "https://cdn.dummyjson.com/product-images/8/thumbnail.jpg",
  },
  {
    id: 9,
    title: "Infinix INBOOK",
    description: "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
    price: 1099,
    stock: 96,
    vote: 64,
    thumbnail: "https://cdn.dummyjson.com/product-images/9/thumbnail.jpg",
  },
  {
    id: 10,
    title: "HP Pavilion 15-DK1056WM",
    description: "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
    price: 1099,
    stock: 89,
    vote: 83,
    thumbnail: "https://cdn.dummyjson.com/product-images/10/thumbnail.jpeg",
  },
  {
    id: 11,
    title: "perfume Oil",
    description: "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
    price: 13,
    stock: 65,
    vote: 85,
    thumbnail: "https://cdn.dummyjson.com/product-images/11/thumbnail.jpg",
  },
  {
    id: 12,
    title: "Brown Perfume",
    description: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
    price: 40,
    stock: 52,
    vote: 4,
    thumbnail: "https://cdn.dummyjson.com/product-images/12/thumbnail.jpg",
  }
];